<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Foundation: identity, organisation, RBAC, services & controlled vocabulary.
 * Human-readable primary keys (EMP-0001, CLI-0001, ...) are generated by the
 * IdGenerator service and never edited manually (system principle).
 */
return new class extends Migration {
    public function up(): void
    {
        // ─── Sequence holder for automatic human-readable IDs ───
        Schema::create('id_sequences', function (Blueprint $table): void {
            $table->string('prefix')->primary();
            $table->unsignedBigInteger('last_value')->default(0);
            $table->timestampsTz();
        });

        // ─── Organisation ───
        Schema::create('departments', function (Blueprint $table): void {
            $table->string('department_id')->primary();
            $table->string('code')->unique();
            $table->string('name');
            $table->string('parent_id')->nullable();
            $table->string('head_employee_id')->nullable();
            $table->boolean('is_active')->default(true);
            $table->timestampsTz();
            $table->foreign('parent_id')->references('department_id')->on('departments')->nullOnDelete();
        });

        // ─── RBAC ───
        Schema::create('roles', function (Blueprint $table): void {
            $table->string('role_id')->primary();
            $table->string('name');
            $table->text('description')->nullable();
            $table->unsignedTinyInteger('level')->default(50);
            $table->boolean('is_active')->default(true);
            $table->timestampsTz();
        });

        Schema::create('permissions', function (Blueprint $table): void {
            $table->string('permission_id')->primary();
            $table->string('module');
            $table->string('name');
            $table->string('description')->nullable();
            $table->timestampsTz();
        });

        Schema::create('role_permission', function (Blueprint $table): void {
            $table->string('role_id');
            $table->string('permission_id');
            $table->string('scope')->default('department'); // all | department | own
            $table->primary(['role_id', 'permission_id']);
            $table->foreign('role_id')->references('role_id')->on('roles')->cascadeOnDelete();
            $table->foreign('permission_id')->references('permission_id')->on('permissions')->cascadeOnDelete();
        });

        // Which modules a department owns fully vs. only reads (read / full / related).
        Schema::create('department_module_access', function (Blueprint $table): void {
            $table->id();
            $table->string('department_id');
            $table->string('module');               // dashboard|admin|crm|sales|project|inventory|finance|hr
            $table->string('access_level');         // full | related | read
            $table->timestampsTz();
            $table->foreign('department_id')->references('department_id')->on('departments')->cascadeOnDelete();
        });

        // ─── Employee master (source of identity & access role) ───
        Schema::create('employees', function (Blueprint $table): void {
            $table->string('employee_id')->primary();
            $table->string('name');
            $table->string('email')->unique();
            $table->string('phone')->nullable();
            $table->string('department_id');
            $table->string('sub_team')->nullable();
            $table->string('position')->nullable();
            $table->string('access_role')->default('staff');
            $table->string('manager_employee_id')->nullable();
            $table->date('start_date')->nullable();
            $table->string('contract_status')->default('Contract'); // Contract | Probation | Permanent
            $table->string('status')->default('active');            // active | inactive | archive
            $table->boolean('is_active')->default(true);
            $table->timestampTz('archived_at')->nullable();
            $table->timestampsTz();
            $table->foreign('department_id')->references('department_id')->on('departments');
            $table->foreign('manager_employee_id')->references('employee_id')->on('employees')->nullOnDelete();
        });

        Schema::table('departments', function (Blueprint $table): void {
            $table->foreign('head_employee_id')->references('employee_id')->on('employees')->nullOnDelete();
        });

        // ─── Supabase auth → employee mapping (1:1) ───
        Schema::create('user_profiles', function (Blueprint $table): void {
            $table->uuid('id')->primary();
            $table->string('auth_user_id')->unique();
            $table->string('employee_id')->nullable()->unique();
            $table->string('name');
            $table->string('email')->nullable()->index();
            $table->string('role')->default('staff')->index();      // cache of employee.access_role
            $table->string('department_id')->nullable()->index();
            $table->boolean('is_active')->default(true);
            $table->timestampsTz();
            $table->foreign('employee_id')->references('employee_id')->on('employees')->nullOnDelete();
            $table->foreign('department_id')->references('department_id')->on('departments')->nullOnDelete();
        });

        // ─── Service lines & default task templates ───
        Schema::create('services', function (Blueprint $table): void {
            $table->string('service_id')->primary();
            $table->string('name');
            $table->text('description')->nullable();
            $table->boolean('is_active')->default(true);
            $table->unsignedSmallInteger('sort_order')->default(0);
            $table->timestampsTz();
        });

        Schema::create('service_templates', function (Blueprint $table): void {
            $table->string('template_id')->primary();   // e.g. PR-01
            $table->string('service_id');
            $table->string('step_name');
            $table->unsignedTinyInteger('sequence');
            $table->boolean('is_default')->default(true);
            $table->timestampsTz();
            $table->foreign('service_id')->references('service_id')->on('services')->cascadeOnDelete();
        });

        // ─── Controlled vocabulary / status master ───
        Schema::create('status_masters', function (Blueprint $table): void {
            $table->id();
            $table->string('category');                 // deal_stage|project_status|task_status|...
            $table->string('status_key');
            $table->string('label');
            $table->string('color')->default('#2c6eaa');
            $table->unsignedSmallInteger('sort_order')->default(0);
            $table->boolean('is_active')->default(true);
            $table->timestampsTz();
            $table->unique(['category', 'status_key']);
        });

        // ─── Global key/value settings (integration toggles, thresholds) ───
        Schema::create('settings', function (Blueprint $table): void {
            $table->string('skey')->primary();
            $table->text('value')->nullable();
            $table->string('group')->default('general');
            $table->timestampsTz();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('settings');
        Schema::dropIfExists('status_masters');
        Schema::dropIfExists('service_templates');
        Schema::dropIfExists('services');
        Schema::dropIfExists('user_profiles');
        Schema::table('departments', fn (Blueprint $t) => $t->dropForeign(['head_employee_id']));
        Schema::dropIfExists('employees');
        Schema::dropIfExists('department_module_access');
        Schema::dropIfExists('role_permission');
        Schema::dropIfExists('permissions');
        Schema::dropIfExists('roles');
        Schema::dropIfExists('departments');
        Schema::dropIfExists('id_sequences');
    }
};